dist: trusty
language: go
go:
  - "1.13"
addons:
  sonarcloud:
    organization: "teemoo7-github"
before_install:
  - go get github.com/stretchr/testify/assert
before_script:
  - go get -d ./...
script:
  - go build ./...
  - go test -v -coverprofile=cov.out ./...
  - sonar-scanner
